steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'gcloud'
  - 'functions'
  - 'deploy'
  - 'bcheena-test-func'
  - '--trigger-resource=bcheena-test-bucket-$PROJECT_ID'
  - '--entry-point=print_logs'
  - '--trigger-event=google.storage.object.finalize'
  - '--source=.'
  - '--region=us-central1'
  - '--runtime=python312'
  - '--project=$PROJECT_ID'
  - '--memory=8192'
  - '--update-env-vars="GCP_PROJECT=$PROJECT_ID"'
  - '--service-account=$PROJECT_NUMBER-compute@developer.gserviceaccount.com'
  - '--no-gen2'
