steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'gcloud'
  - 'functions'
  - 'deploy'
  - '$_FUNCTION_NAME'
  - '--trigger-resource=$_BUCKET_NAME'
  - '--entry-point=$_ENTRY_POINT'
  - '--trigger-event=google.storage.object.finalize'
  - '--source=.'
  - '--region=us-central1'
  - '--runtime=python312'
  - '--project=$PROJECT_ID'
  - '--memory=8192'
  - '--update-env-vars="GCP_PROJECT=$PROJECT_ID"'
  - '--service-account=$PROJECT_NUMBER-compute@developer.gserviceaccount.com'
  - '--no-gen2'


substitutions:
  _FUNCTION_NAME: "bcheena-test-func"
  _BUCKET_NAME: "bcheena-test-bucket-$PROJECT_ID"
  _ENTRY_POINT: "print_logs"
